$(document).ready(function(){
	cargar_contenido('#1_port','1_portada.html');
	cargar_contenido('#2_int','2_intro.html');
	cargar_contenido('#3_arq','3_arquitectura.html');
	cargar_contenido('#4_cback','4_caract_back.html');
	cargar_contenido('#5_cfron','5_caract_front.html');
	cargar_contenido('#6_dif','6_diferencias.html');
    cargar_contenido('#6_dif_cont','6_diferen_cont.html');
    cargar_contenido('#7_enlace','7_enlace_interes.html');
    cargar_contenido('#8_final','8_final.html');
});
